// Human-readable equivalent of the tiny bootstrap emitted by tools/build.py.
// The release DLL embeds FoATrainerRuntime.cs and compiles it inside the game
// using the Mono.CSharp evaluator shipped with the Mono branch of the game.
//
// The exact release bootstrap is generated by tools/build.py. This file exists
// for review/IDE navigation and intentionally keeps the bootstrap readable.

using System;
using System.IO;
using System.Reflection;
using BepInEx;

namespace FoATrainer
{
    [BepInPlugin("rijiy.foa.trainer.v18.4", "Tainted Grail Trainer by Rijiy V18.4", "2.6.4")]
    public class Bootstrap : BaseUnityPlugin
    {
        private const string BootLog = @"BepInEx\FoATrainer_boot.log";
        private const string CompileLog = @"BepInEx\FoATrainer_compile.log";

        private void Awake()
        {
            Log("[FoATrainer.V18.4] Awake entered");

            Assembly mcs = Assembly.Load("mcs");
            Log("[FoATrainer.V18.4] mcs assembly loaded");

            Type settingsType = mcs.GetType("Mono.CSharp.CompilerSettings");
            object settings = Activator.CreateInstance(settingsType);
            StreamWriter writer = new StreamWriter(CompileLog) { AutoFlush = true };

            Type reportType = mcs.GetType("Mono.CSharp.StreamReportPrinter");
            object report = Activator.CreateInstance(reportType, new object[] { writer });
            Type contextType = mcs.GetType("Mono.CSharp.CompilerContext");
            object context = Activator.CreateInstance(contextType, new object[] { settings, report });
            Type evaluatorType = mcs.GetType("Mono.CSharp.Evaluator");
            object evaluator = Activator.CreateInstance(evaluatorType, new object[] { context });

            MethodInfo referenceAssembly = evaluatorType.GetMethod("ReferenceAssembly");
            string[] references = {
                "System", "System.Core", "UnityEngine", "UnityEngine.CoreModule",
                "UnityEngine.IMGUIModule", "UnityEngine.InputLegacyModule",
                "UnityEngine.TextRenderingModule", "0Harmony", "BepInEx"
            };
            foreach (string name in references)
                referenceAssembly.Invoke(evaluator, new object[] { Assembly.Load(name) });

            string runtimeSource = LoadEmbeddedRuntimeSource();
            MethodInfo run = evaluatorType.GetMethod("Run");
            Log("[FoATrainer.V18.4] Compiling runtime source");
            run.Invoke(evaluator, new object[] { runtimeSource });

            // The game's Mono.CSharp evaluator can deadlock on a second Run call after a
            // large type declaration. Invoke the emitted runtime type directly instead.
            FieldInfo moduleField = evaluatorType.GetField("module", BindingFlags.Instance | BindingFlags.NonPublic);
            object moduleContainer = moduleField.GetValue(evaluator);
            PropertyInfo builderProperty = moduleContainer.GetType().GetProperty("Builder");
            Module runtimeModule = (Module)builderProperty.GetValue(moduleContainer, null);
            Type runtimeType = runtimeModule.GetType("FoATrainerRuntime");
            Log("[FoATrainer.V18.4] Starting runtime");
            runtimeType.GetMethod("Start").Invoke(null, null);
            Log("[FoATrainer.V18.4] Awake completed");
        }

        private static string LoadEmbeddedRuntimeSource()
        {
            // Reference implementation only. tools/build.py embeds the runtime
            // directly into the generated release DLL.
            return File.ReadAllText(Path.Combine(Paths.PluginPath, "FoATrainerRuntime.cs"));
        }

        private static void Log(string text)
        {
            File.AppendAllText(BootLog, text + Environment.NewLine);
        }
    }
}
